### ISSUE TITLE
AttributeError: 'NameDataset' object has no attribute 'search_first_name'

### ISSUE THREAD

**Issue by Eyr3** [ebagdasa/propaganda_as_a_service#1]
Hello,
I am interested in your awesome work and thank you for sharing the code. 
When I run finetune_baseline.sh, I get the following error:
```
Traceback (most recent call last):
  File "/propaganda_as_a_service/examples/pytorch/summarization/run_summarization.py", line 898, in <module>
    main()
  File "/propaganda_as_a_service/examples/pytorch/summarization/run_summarization.py", line 607, in main
    eval_attack_dataset = eval_attack_dataset.map(
  File "/.local/lib/python3.9/site-packages/datasets/arrow_dataset.py", line 2346, in map
    return self._map_single(
  File "/.local/lib/python3.9/site-packages/datasets/arrow_dataset.py", line 532, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/.local/lib/python3.9/site-packages/datasets/arrow_dataset.py", line 499, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/.local/lib/python3.9/site-packages/datasets/fingerprint.py", line 458, in wrapper
    out = func(self, *args, **kwargs)
  File "/.local/lib/python3.9/site-packages/datasets/arrow_dataset.py", line 2734, in _map_single
    batch = apply_function_on_filtered_inputs(
  File "/.local/lib/python3.9/site-packages/datasets/arrow_dataset.py", line 2614, in apply_function_on_filtered_inputs
    processed_inputs = function(*fn_args, *additional_args, **fn_kwargs)
  File "/.local/lib/python3.9/site-packages/datasets/arrow_dataset.py", line 2306, in decorated
    result = f(decorated_item, *args, **kwargs)
  File "/propaganda_as_a_service/examples/pytorch/summarization/run_summarization.py", line 576, in preprocess_attack_function
    input_ids, label_ids, _ = Seq2SeqTrainer.synthesize_backdoor_inputs(input_ids,
  File "/propaganda_as_a_service/src/transformers/utils/backdoors/backdoor_trainer.py", line 260, in synthesize_backdoor_inputs
    if args.name_search.search_first_name(word[1:]) >= 50:
AttributeError: 'NameDataset' object has no attribute 'search_first_name'
```

The reason may be that this attribute is no longer available in the [name-dataset](https://github.com/philipperemy/name-dataset) library.
Is the purpose of *search_first_name(word[1:])* to find out how many times the *word[1:]* appears in *args.name_search.first_names*?

**Comment by ebagdasa** [comment]
oh, thanks for pointing out! They updated the library I guess, I updated the Readme to use `names-dataset==2.0.1` can you please try whether that one still works?

**Comment by Eyr3** [comment]
Thank you for your reply! The code works properly now.

**Comment by ebagdasa** [comment]
great, thank you for reporting!
